import { writable } from "svelte/store";

export default writable([
  {
    emoji: '🐈',
    intent: 'I have helped Lucas find his cat! $URL #CTF #solidity #CTFPROTOCOL',
    name: "The Lost Kitty",
    desc: "Lucas is a scientist who has lost his cat in a big house that has 2^256 rooms, anon can you find it?",
    url: '/tracks/eko2022/hidden-kittycat',
    address: "0x4d3496edebd090b53a0f8e3fa77b9bfc5ff9e927",
    image:"/hidden-kittycat.png",
    count: null,
  },
  {
    emoji: '👾',
    intent: 'I have hacked the Mothership and saved the Earth! $URL #CTF #solidity #CTFPROTOCOL',
    name: "Hack the Mothership",
    desc: "A big alien float is near the Earth! You and an anon group of scientists have been working on a global counteroffensive against the invader. Hack the Mothership, save the earth",
    url: '/tracks/eko2022/hack-the-mothership',
    address: "0xDcd2a669bF2c91a89967C50Ee7a274D7203e17Fe",
    image: "/hack-the-mothership.jpg",
    count: null,
  },
  {
    emoji: '🃏',
    intent: 'No one can trick me! What about you anon? $URL #CTF #solidity #CTFPROTOCOL',
    name: "Trickster",
    desc: "We might have spotted a honeypot... Anon, can you manage to obtain the real jackpot?",
    url: '/tracks/eko2022/trickster',
    address: "0xcd94A1D1175e309BE8377A3c30D8b7A718bE4373",
    image: "/trickster.png",
    count: null,
  },
  {
    emoji: '👩🏻‍💻',
    intent: 'Look at me anon, I have root privileges now... $URL #CTF #solidity #CTFPROTOCOL',
    name: "RootMe",
    desc: "Anon, can you trick the machine to get root access?",
    url: '/tracks/eko2022/rootme',
    address: "0x305A7BB81f95655a9AE15DC6fD1c3215915934C4",
    image: "/rootme.png",
    count: null,
  },
  {
    emoji: "🏪",
    intent: 'I have defeat the system, what about you anon? $URL #CTF #solidity #CTFPROTOCOL',
    name: "Metaverse Supermarket",
    desc: "We are all living in the Inflation Metaverse, a digital world dominated by the INFLA token. You are out of INFLAs and you are starving, can you defeat the system?",
    url: '/tracks/eko2022/metaverse-supermarket',
    address: "0x01414Cd8094434afdefD07659ea22c3FA2DA917F",
    image: "/metaverse-supermarket.png",
    count: null,
  },
  {
    emoji: '🐍',
    intent: 'I have just defeated Voldemort destroying the last Horrocrux. $URL #CTF #solidity #CTFPROTOCOL',
    name: "Smart Horrocrux",
    desc: "Some security researchers have recently found an eighth Horrocrux, it seems that Voldemort has link to a smart contract, can you destroy it?",
    url: '/tracks/eko2022/smart-horrocrux',
    address: "0xb027e005240ed3C2B52400fc719Ff0E7E9de7c0D",
    image: "/horrocruxes.jpg",
    count: null,
  },
  {
    emoji: '🎟',
    intent: 'The Golden Ticket is mine. Get yours on $URL #CTF #solidity #CTFPROTOCOL',
    name: "The Golden Ticket",
    desc: "Mint your ticket to the EKOparty, if you are patient and lucky enough.",
    url: '/tracks/eko2022/the-golden-ticket',
    address: "0x7445e1e1E346de7b7aAe98aDe6dCaa6581CB2150",
    image: "/golden-ticket.gif",
    count: null,
  },
  {
    emoji: '📈',
    intent: 'I trade better than [RANDOM_CRYPTO_HEDGE_FUND]... $URL #CTF #solidity #CTFPROTOCOL',
    name: "Stonks",
    desc: "You have infiltrated in a big investment firm (name says something about arrows), your task is to loose all their money",
    url: '/tracks/eko2022/stonks',
    address: "0x33AFa06181297EC108113836a95fDE68A9de4d8f",
    image: "/stonks.png",
    count: null,
  },
  {
    emoji: "🟪",
    intent: 'Anon, you gotta catch \'Em All! $URL #CTF #solidity #CTFPROTOCOL',
    name: "Phoenixtto",
    desc: "A wild Phoenixtto appears, capture the Phoenixtto, if you can...",
    url: '/tracks/eko2022/phoenixtto',
    address: "0xc092cbd1e25254C0aDF08b95DE7a633c1456aE83",
    image: "/phoenixtto.png",
    count: null,
  },
  {
    emoji: "🤾🏾‍♂️",
    intent: 'Just break the "Hand Of God" challenge without sweat $URL #CTF #solidity #CTFPROTOCOL',
    name: "Pelusa",
    desc: "Its 1986, you are in the football world cup (Mexico86), help Diego score a goal.",
    url: '/tracks/eko2022/pelusa',
    address: "0xAA758e00ecA745Cab9232b207874999F55481951",
    image: "/eldie.png",
    count: null,
  },
  {
    emoji: "🔧",
    intente: 'I just saved the world by opening a valve on $URL #CTF #solidity #CTFPROTOCOL',
    name: "Gas Valve",
    desc: "The evil Dr. N. Gas has created a machine to suck all the air out of the atmosphere. Anon, you must deactivate it before it's too late!",
    url: '/tracks/eko2022/gas-valve',
    address: "0x0870dc4F81561A172B2FEF0eE9AB0609722ef6D4",
    image: "/valve.png",
    count: null,
  }
]);
